//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianSyncConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityGroups : IEntityId
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> DefaultFlag { get; set; }
        public Nullable<bool> DataExtractFlag { get; set; }
        public Nullable<long> UpdatedById { get; set; }
        public string UpdatedByExternalId { get; set; }
        public string ExternalId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
