//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianSyncConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments : IEntityId
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> RequestId { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<long> UpdatedById { get; set; }
        public string UpdatedByExternalId { get; set; }
        public Nullable<long> AttachmentTypeId { get; set; }
        public string RequestExternalId { get; set; }
        public string Contents { get; set; }
        public Nullable<bool> IsSignature { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
