//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianSyncConsole.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GuardianStagingEntities : DbContext
    {
        public GuardianStagingEntities()
            : base("name=GuardianStagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<ActivityGroups> ActivityGroups { get; set; }
        public virtual DbSet<ApplicationUsers> ApplicationUsers { get; set; }
        public virtual DbSet<Assets> Assets { get; set; }
        public virtual DbSet<Attachments> Attachments { get; set; }
        public virtual DbSet<BillCodes> BillCodes { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<GuardianVM> GuardianVM { get; set; }
        public virtual DbSet<LaborCosts> LaborCosts { get; set; }
        public virtual DbSet<LaborRateScheduleBillingRates> LaborRateScheduleBillingRates { get; set; }
        public virtual DbSet<LaborRateSchedules> LaborRateSchedules { get; set; }
        public virtual DbSet<OtherCosts> OtherCosts { get; set; }
        public virtual DbSet<PriorityTypeSlaDetails> PriorityTypeSlaDetails { get; set; }
        public virtual DbSet<Properties> Properties { get; set; }
        public virtual DbSet<RegionRegionAssociations> RegionRegionAssociations { get; set; }
        public virtual DbSet<Regions> Regions { get; set; }
        public virtual DbSet<Schedules> Schedules { get; set; }
        public virtual DbSet<ServiceTypes> ServiceTypes { get; set; }
        public virtual DbSet<Spaces> Spaces { get; set; }
        public virtual DbSet<UserApiModels> UserApiModels { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkOrderMaterialCostLineItems> WorkOrderMaterialCostLineItems { get; set; }
        public virtual DbSet<Workorders> Workorders { get; set; }
        public virtual DbSet<WorkOrderChargeToAccounts> WorkOrderChargeToAccounts { get; set; }
    }
}
