//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianSyncConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaborCosts : IEntityId
    {
        public long Id { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string ExternalEmployeeId { get; set; }
        public Nullable<System.DateTime> TimeStarted { get; set; }
        public Nullable<System.DateTime> TimeFinished { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<long> RateTypeId { get; set; }
        public Nullable<long> RequestTypeActivityId { get; set; }
        public string ExternalRequestTypeActivityId { get; set; }
        public string ApInvoiceNumber { get; set; }
        public string ApAccountNumber { get; set; }
        public Nullable<int> LienWaiverAmount { get; set; }
        public string LienWaiverComments { get; set; }
        public string PaymentComments { get; set; }
        public Nullable<int> ApInvoiceAmount { get; set; }
        public Nullable<System.DateTime> ApPostDate { get; set; }
        public Nullable<System.DateTime> ApDueDate { get; set; }
        public Nullable<int> ApTaxAmount { get; set; }
        public Nullable<int> ApShippingHandlingAmount { get; set; }
        public Nullable<long> ApInvoiceStatusId { get; set; }
        public Nullable<System.DateTime> ApInvoiceDate { get; set; }
        public Nullable<long> CoaAccountId { get; set; }
        public string Payee { get; set; }
        public Nullable<int> TaxAmount { get; set; }
        public Nullable<int> BudgetYear { get; set; }
        public string VendorCode { get; set; }
        public string VendorCompanyExternalId { get; set; }
        public Nullable<long> CrewId { get; set; }
        public Nullable<long> InstallId { get; set; }
        public Nullable<long> RequestId { get; set; }
        public string RequestExternalId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<long> VendorCompanyId { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<bool> MarkupFlag { get; set; }
        public Nullable<int> TotalMarkup { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<long> RecurrenceId { get; set; }
        public Nullable<long> UpdatedById { get; set; }
        public Nullable<bool> AccountsPayableFlag { get; set; }
        public Nullable<bool> ApExportFlag { get; set; }
        public Nullable<bool> TaxableFlag { get; set; }
        public string CurrencySign { get; set; }
        public Nullable<int> LineItemNumber { get; set; }
        public Nullable<long> ExternalId { get; set; }
        public Nullable<int> TaxRate { get; set; }
        public string ExternalUpdatedById { get; set; }
        public string ExternalRecurrenceId { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
    }
}
