//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianSyncConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityTypeSlaDetails : IEntityId
    {
        public long Id { get; set; }
        public Nullable<long> RequestPriorityId { get; set; }
        public Nullable<long> RequestTypeId { get; set; }
        public Nullable<int> DefaultFollowupAlert { get; set; }
        public Nullable<long> EscalateToId { get; set; }
        public Nullable<int> DefaultSlaResponseTime { get; set; }
        public Nullable<int> DefaultSlaCompletionTime { get; set; }
        public Nullable<int> SlaOverdueAlert { get; set; }
        public Nullable<long> SlaEscalateToId { get; set; }
        public Nullable<bool> SlaSendNotificationsFlag { get; set; }
        public Nullable<long> UpdatedById { get; set; }
        public Nullable<bool> Sla247OverrideFlag { get; set; }
        public Nullable<long> RequestSubTypeId { get; set; }
        public Nullable<bool> DefaultPriorityFlag { get; set; }
        public Nullable<bool> SlaCompletionInHours { get; set; }
        public Nullable<bool> SlaResponseInHours { get; set; }
        public string UpdatedByExternalId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
