//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianSyncConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionRegionAssociations : IEntityId
    {
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<long> ParentExternalId { get; set; }
        public Nullable<long> ChildId { get; set; }
        public Nullable<long> ChildExternalId { get; set; }
        public Nullable<long> UpdatedById { get; set; }
        public string UpdatedByExternalId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
