//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianSyncConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules: IEntityId
    {
        public long Id { get; set; }
        public string ExternalId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> AssetId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> RequestTypeId { get; set; }
        public Nullable<long> RequestSubTypeId { get; set; }
        public string ScheduleName { get; set; }
        public string RecurrencePatternDesc { get; set; }
        public Nullable<long> AssignedToId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
