//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianSyncConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderChargeToAccounts : IEntityId
    {
        public long Id { get; set; }
        public string RequestId { get; set; }
        public string RequestExternalId { get; set; }
        public string Description { get; set; }
        public string Number { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
