//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuardianSyncConsole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderMaterialCostLineItems
    {
        public long Id { get; set; }
        public Nullable<long> RequestedId { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public string ChargeToAccountNumber { get; set; }
        public string ChargetoAccount { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UnitCost { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
